# Generated by Django 3.2.4 on 2023-05-17 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=25)),
                ('doj', models.DateTimeField()),
            ],
            options={
                'ordering': ('-doj',),
            },
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=25)),
                ('doj', models.DateTimeField()),
            ],
            options={
                'ordering': ('-doj',),
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_name', models.CharField(max_length=50)),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('picture', models.FileField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=2500)),
                ('male_category', models.BooleanField(default=False)),
                ('female_category', models.BooleanField(default=False)),
                ('doa', models.DateTimeField()),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.seller')),
            ],
            options={
                'ordering': ('doa',),
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.customer')),
            ],
        ),
    ]
